### ISSUE TITLE
Is there a limit as to how many emails can be sent with email posts commentators?

### ISSUE THREAD

**Issue by pdeleff** [ashfame/email-posts-commentators#1]
I tried using the plug in for the first time and instead of emailing all my commentators (numbering in the thousands) it only emailed 60. Just wondering what was up with that? Any way of emailing all of them at the same time, or maybe figuring out who I just sent an email to? Thanks for your help.

Peter Deleff

**Comment by ashfame** [comment]
@pdeleff Sorry never saw this until now. My best guess would be that it hit your PHP's execution time limit which is usually 30 seconds and it could only process that much. Its a very basic plugin and when I build it for my needs, it did a few hundreds with ease.
